name: Checks

on:
  pull_request

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '17.6.0'
      - run: sudo apt-get update
      - run: sudo apt-get install -y libappindicator1 fonts-liberation xvfb
      - run: export CHROME_BIN=/usr/bin/google-chrome
      - run: export DISPLAY=:99.0
      - run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo dpkg -i google-chrome*.deb
      - run: yarn
      - run: yarn add node-forge -P
      - run: xvfb-run --auto-servernum yarn test
      
